export type { RecommendationStrategy } from './RecommendationStrategy'
export { RecommendationEngine } from './RecommendationEngine'
export { AddTestingStrategy } from './strategies/AddTestingStrategy'
export { AddCIStrategy } from './strategies/AddCIStrategy'
export { AddTypeScriptStrategy } from './strategies/AddTypeScriptStrategy'
