/**
 * BudgetPolicy controls LLM spending limits.
 *
 * Scope: BudgetPolicy defines requested limits. It does NOT own spend accounting.
 * dailySpendUsd is supplied by an external usage/telemetry service.
 * The agent does not calculate or persist the spend generated by its own request.
 *
 * maxTokensPerRequest: maximum output tokens per single provider call.
 * maxAttempts: maximum provider calls per operation (initial + retries).
 * maxDailyCostUsd: daily spending cap (null = no limit). Evaluated against
 *   the externally-provided dailySpendUsd value.
 * fallbackToMock: when true, switch to MockLLMProvider when limits are exceeded.
 */
export interface BudgetPolicy {
  maxTokensPerRequest: number
  maxAttempts: number // max total attempts (initial + retries)
  maxDailyCostUsd: number | null // null = no limit
  fallbackToMock: boolean
}

// Budget semantics:
// - maxTokensPerRequest = maximum output allocation per provider call
// - maxAttempts = maximum provider calls per operation
// - Total possible tokens per operation = maxTokensPerRequest * maxAttempts
// - Usage tracking: agent aggregates initial + retry usage into a single total

export const DevelopmentBudgetPolicy: BudgetPolicy = {
  maxTokensPerRequest: 4000,
  maxAttempts: 2,
  maxDailyCostUsd: 0, // $0 — always use mock in dev
  fallbackToMock: true,
}

export const StagingBudgetPolicy: BudgetPolicy = {
  maxTokensPerRequest: 4000,
  maxAttempts: 3,
  maxDailyCostUsd: 5.0, // $5/day
  fallbackToMock: true,
}

export const ProductionBudgetPolicy: BudgetPolicy = {
  maxTokensPerRequest: 8000,
  maxAttempts: 3,
  maxDailyCostUsd: null, // unlimited — monitored via telemetry
  fallbackToMock: false,
}

export function shouldFallbackToMock(
  policy: BudgetPolicy,
  estimatedTokens: number,
  dailySpendUsd: number
): boolean {
  if (estimatedTokens > policy.maxTokensPerRequest) return policy.fallbackToMock
  if (policy.maxDailyCostUsd !== null && dailySpendUsd >= policy.maxDailyCostUsd)
    return policy.fallbackToMock
  return false
}
